spring:
  datasource:
    continue-on-error: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/programs_tj?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
#    password: your127@
  mvc:    view:      suffix: .html
mybatis:  mapper-locations:  - classpath:mapper/*.xml
  
